apiVersion: apps/v1
kind: Deployment
metadata:
  name: net-tools
  labels:
    app: net-tools
spec:
  replicas: 1
  selector:
    matchLabels:
       app: net-tools
  template:
    metadata:
      labels:
        name: net-tools
    spec:
      containers:
      - name: net-tools
        image: donch/net-tools:latest
        args:
        - sleep
        - "300000000"
