name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: Install Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: late
    - name: Login to Docker Hub
      run: echo "${{ secrets.DH_PASSWORD }}" | docker login -u "${{ secrets.DH_LOGIN }}" --password-stdin
    - name: Build and push
      run: |
        docker buildx build --push \
          --tag donch/net-tools:latest \
          --platform linux/amd64,linux/arm/v7,linux/arm64 .
