name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Install Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        version: late

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DH_LOGIN }}
        password: ${{ secrets.DH_PASSWORD }}

    - name: Generate image metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ github.repository }}

    - name: Push container images tag (Latest)
      uses: docker/build-push-action@v4
      with:
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        push: true
        labels: ${{ steps.meta.outputs.labels }}
        tags: |
          ${{ github.repository }}:latest
